# Feature Engineering and Pre-processing
### Blaine Murphy -- September 2021

In this notebook I need to 
- Encode categorical columns
- Calculate information value for all columns to whether there was a purchase and cull columns that don't provide any information value
- Calculate multicollinearity among the features and remove those that don't offer additional information 
- Format the data into a tensor for input to RNN model
    - Find maximum number of repeated visits
    - Scaling??
    - Aggregate users and reshape data to [batch,maximum number of repeat visits,# of predictive features]
    - The second dimension will house the purchase amount of each visit and the 3rd dimension will have all of the predictive features
    - Split users into train, validation, test sets

In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
os.chdir(r'D:\Springboard\Capstone 3 maybe\Google Analytics')
os.listdir()

['e390021b-3cdc-4df0-b92e-22082e3ad15b_Data.csv',
 'GDP by Country world bank.csv',
 'life expectency by country_world bank.csv',
 'Metadata_Country_API_NY.GDP.MKTP.CD_DS2_en_csv_v2_2763936.csv',
 'Metadata_Country_API_SP.DYN.LE00.IN_DS2_en_csv_v2_2764094.csv',
 'Metadata_Country_API_SP.POP.TOTL_DS2_en_csv_v2_2763937.csv',
 'Metadata_Indicator_API_NY.GDP.MKTP.CD_DS2_en_csv_v2_2763936.csv',
 'Metadata_Indicator_API_SP.DYN.LE00.IN_DS2_en_csv_v2_2764094.csv',
 'Metadata_Indicator_API_SP.POP.TOTL_DS2_en_csv_v2_2763937.csv',
 'Population by country world bank.csv',
 'sample_submission.csv',
 'sample_submission_v2.csv',
 'test.csv',
 'test_v2.csv',
 'train.csv',
 'train_eda.csv',
 'train_v2.csv',
 'train_wrangled.csv',
 'worldpopulationreview.com']

In [3]:
train = pd.read_csv('train_eda.csv',index_col=0,parse_dates=['date','dateTime'])
train.info()

C:\Users\blain\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 901907 entries, 0 to 903652
Data columns (total 50 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   channelGrouping                          901907 non-null  object
 1   date                                     901907 non-null  datetime64[ns]
 2   fullVisitorId                            901907 non-null  object
 3   sessionId                                901907 non-null  object
 4   visitId                                  901907 non-null  int64
 5   visitNumber                              901907 non-null  int64
 6   visitStartTime                           901907 non-null  int64
 7   browser                                  901907 non-null  object
 8   operatingSystem                          901907 non-null  object
 9   isMobile                                 901907 non-null  int64
 10  deviceCategory                           901907 non-null  object
 11  continent                                901907 non-null  object
 12  subContinent                             901907 non-null  object
 13  country                                  901907 non-null  object
 14  region                                   901907 non-null  object
 15  metro                                    901907 non-null  object
 16  city                                     901907 non-null  object
 17  campaign                                 901907 non-null  object
 18  source                                   901907 non-null  object
 19  keyword                                  400041 non-null  object
 20  hits                                     901907 non-null  int64
 21  pageviews                                901907 non-null  int64
 22  bounces                                  901907 non-null  int64
 23  newVisits                                901907 non-null  int64
 24  transactionRevenue                       901907 non-null  int64
 25  dollars                                  901907 non-null  float64
 26  purchase                                 901907 non-null  int64
 27  dateTime                                 901907 non-null  datetime64[ns]
 28  hour                                     901907 non-null  int64
 29  weekend                                  901907 non-null  int64
 30  month                                    901907 non-null  int64
 31  time                                     901907 non-null  float64
 32  timeDiffLastVisit                        189072 non-null  float64
 33  countryPopulation                        901907 non-null  float64
 34  countryGDP                               901907 non-null  float64
 35  countryLE                                901907 non-null  float64
 36  state                                    901907 non-null  object
 37  keywordStore                             901907 non-null  int64
 38  keywordMerch                             901907 non-null  int64
 39  keywordShirt                             901907 non-null  int64
 40  keywordGoogle                            901907 non-null  int64
 41  keywordYoutube                           901907 non-null  int64
 42  keywordShop                              901907 non-null  int64
 43  keywordApparel                           901907 non-null  int64
 44  keyword_(Remarketing/Content targeting)  901907 non-null  int64
 45  keyword_(User vertical targeting)        901907 non-null  int64
 46  keyword_(automatic matching)             901907 non-null  int64
 47  keyword_(content targeting)              901907 non-null  int64
 48  keyword_(not provided)                   901907 non-null  int64
 49  keyword_search                           901907 non-null  int64
dtypes: datetime64[ns](2), float64(6), int64(26), object(16)
memory usage: 350.9+ MB

A couple of columns to fix. `keyword` is mostly null and I already created new columns from it based on the most frequent search words that resulted in a purchase.  I can drop it now.  

And `timeDiffLastVisit` is mostly null because most of the records are new visits, not repeat visits.  I will fill all of those nulls with the maximum of the `timeDiffLastVisit` column.

In [4]:
train.drop('keyword',axis=1,inplace=True)
train['timeDiffLastVisit'] = train.timeDiffLastVisit.fillna(train.timeDiffLastVisit.max())

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 901907 entries, 0 to 903652
Data columns (total 49 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   channelGrouping                          901907 non-null  object
 1   date                                     901907 non-null  datetime64[ns]
 2   fullVisitorId                            901907 non-null  object
 3   sessionId                                901907 non-null  object
 4   visitId                                  901907 non-null  int64
 5   visitNumber                              901907 non-null  int64
 6   visitStartTime                           901907 non-null  int64
 7   browser                                  901907 non-null  object
 8   operatingSystem                          901907 non-null  object
 9   isMobile                                 901907 non-null  int64
 10  deviceCategory                           901907 non-null  object
 11  continent                                901907 non-null  object
 12  subContinent                             901907 non-null  object
 13  country                                  901907 non-null  object
 14  region                                   901907 non-null  object
 15  metro                                    901907 non-null  object
 16  city                                     901907 non-null  object
 17  campaign                                 901907 non-null  object
 18  source                                   901907 non-null  object
 19  hits                                     901907 non-null  int64
 20  pageviews                                901907 non-null  int64
 21  bounces                                  901907 non-null  int64
 22  newVisits                                901907 non-null  int64
 23  transactionRevenue                       901907 non-null  int64
 24  dollars                                  901907 non-null  float64
 25  purchase                                 901907 non-null  int64
 26  dateTime                                 901907 non-null  datetime64[ns]
 27  hour                                     901907 non-null  int64
 28  weekend                                  901907 non-null  int64
 29  month                                    901907 non-null  int64
 30  time                                     901907 non-null  float64
 31  timeDiffLastVisit                        901907 non-null  float64
 32  countryPopulation                        901907 non-null  float64
 33  countryGDP                               901907 non-null  float64
 34  countryLE                                901907 non-null  float64
 35  state                                    901907 non-null  object
 36  keywordStore                             901907 non-null  int64
 37  keywordMerch                             901907 non-null  int64
 38  keywordShirt                             901907 non-null  int64
 39  keywordGoogle                            901907 non-null  int64
 40  keywordYoutube                           901907 non-null  int64
 41  keywordShop                              901907 non-null  int64
 42  keywordApparel                           901907 non-null  int64
 43  keyword_(Remarketing/Content targeting)  901907 non-null  int64
 44  keyword_(User vertical targeting)        901907 non-null  int64
 45  keyword_(automatic matching)             901907 non-null  int64
 46  keyword_(content targeting)              901907 non-null  int64
 47  keyword_(not provided)                   901907 non-null  int64
 48  keyword_search                           901907 non-null  int64
dtypes: datetime64[ns](2), float64(6), int64(26), object(15)
memory usage: 344.1+ MB

### One hot encoding of categorical columns

In [6]:
"','".join(list(train.columns))

"channelGrouping','date','fullVisitorId','sessionId','visitId','visitNumber','visitStartTime','browser','operatingSystem','isMobile','deviceCategory','continent','subContinent','country','region','metro','city','campaign','source','hits','pageviews','bounces','newVisits','transactionRevenue','dollars','purchase','dateTime','hour','weekend','month','time','timeDiffLastVisit','countryPopulation','countryGDP','countryLE','state','keywordStore','keywordMerch','keywordShirt','keywordGoogle','keywordYoutube','keywordShop','keywordApparel','keyword_(Remarketing/Content targeting)','keyword_(User vertical targeting)','keyword_(automatic matching)','keyword_(content targeting)','keyword_(not provided)','keyword_search"

In [7]:
num_cols = ['isMobile','hits','pageviews','bounces','newVisits',\
        'hour','weekend','month','time','timeDiffLastVisit',\
        'countryPopulation','countryGDP','countryLE','keywordStore',\
        'keywordMerch','keywordShirt','keywordGoogle',\
        'keywordYoutube','keywordShop','keywordApparel',\
        'keyword_(Remarketing/Content targeting)',\
        'keyword_(User vertical targeting)','keyword_(automatic matching)',\
        'keyword_(content targeting)','keyword_(not provided)','keyword_search']

In [8]:
dummy_cols = ['channelGrouping','browser','operatingSystem',\
              'deviceCategory','subContinent','country','city','state',\
              'campaign','source']

In [9]:
X = pd.concat([train[num_cols],pd.get_dummies(train[dummy_cols])], axis=1)

### Information value. 
Calculation of information value to whether there was a purchase or not.
I will drop all of the columns with less than 0.01

In [10]:
### Function to calculate the Information Value (IV) of each feature
### 


max_bin = 20
force_bin = 3
import pandas.core.algorithms as algos
import scipy.stats.stats as stats
import re


# define a binning function
### this function is for binning and calculating the Weight of Evidence 
### for the target and the Information Value for the feature
### and the In
def mono_bin(Y, X, n = max_bin):    
    ### create new dataframe of series feature and series y
    df1 = pd.DataFrame({"X": X, "Y": Y})
    
    ### check to see if any nulls in feature and seperate nulls out
    justmiss = df1[['X','Y']][df1.X.isnull()]
    notmiss = df1[['X','Y']][df1.X.notnull()]
    #print("justmiss", justmiss)
    #print("notmiss", notmiss)
    
    
    ### while loop until Spearman correlation coefficient is between [-1,1]
    ### Finding minumum bin size that results in 'abs(r)' of >1???
    
    r = 0
    while np.abs(r) < 1:
        ### Try creation of new dataframe with max or less bin size 'n'
        ### create dataframe with feature, target and binned feature 
        ### create 'd2' group by object on 'Bucket'
        ### calculate Spearman correlation 'r' and p-value from mean of feature and target
        ### If exception reduce bin number by one and try again
        ### Effectively finding the max bin number that can be used 
        ### for calculating WOE
        try:
            d1 = pd.DataFrame({"X": notmiss.X, "Y": notmiss.Y,\
                               "Bucket": pd.qcut(notmiss.X, n)})
            d2 = d1.groupby('Bucket', as_index=True)
                             
            r, p = stats.spearmanr(d2.mean().X, d2.mean().Y)
            #print("I am here 1",r, n,len(d2))
            n = n - 1 
            
            
        except Exception as e:
            n = n - 1
            #print("I am here e",n)

    ### If length of d2 is 1 (ie 1 bucket for all of feature) do this
    if len(d2) == 1:
        #print("I am second step ",r, n)
        
        ### force 'n' to 3 and calculate quantiles of feature from (0,0.5,1) 
        ### to be used as bins, if not 3 unique because of heavily skewed data
        ### manually create bin
        n = force_bin         
        bins = algos.quantile(notmiss.X, np.linspace(0, 1, n))
        if len(np.unique(bins)) == 2:
            bins = np.insert(bins, 0, 1)
            bins[1] = bins[1]-(bins[1]/2)
            
        ### Create new dataframe bucketed by manual bins
        d1 = pd.DataFrame({"X": notmiss.X, "Y": notmiss.Y, "Bucket": pd.cut(notmiss.X, np.unique(bins),include_lowest=True)}) 
        d2 = d1.groupby('Bucket', as_index=True)
    
    ### Create new dataframe from aggregating the binned dataframe
    d3 = pd.DataFrame({},index=[])
    d3["MIN_VALUE"] = d2.min().X
    d3["MAX_VALUE"] = d2.max().X
    d3["COUNT"] = d2.count().Y
    d3["EVENT"] = d2.sum().Y
    d3["NONEVENT"] = d2.count().Y - d2.sum().Y
    d3=d3.reset_index(drop=True)
    
    if len(justmiss.index) > 0:
        d4 = pd.DataFrame({'MIN_VALUE':np.nan},index=[0])
        d4["MAX_VALUE"] = np.nan
        #print(justmiss.count().Y)
        d4["COUNT"] = justmiss.count().Y
        d4["EVENT"] = justmiss.sum().Y
        d4["NONEVENT"] = justmiss.count().Y - justmiss.sum().Y
        d3 = d3.append(d4,ignore_index=True)
    
    ### add more features to d3 describing the 'events' of the target
    d3["EVENT_RATE"] = d3.EVENT/d3.COUNT
    d3["NON_EVENT_RATE"] = d3.NONEVENT/d3.COUNT
    d3["DIST_EVENT"] = d3.EVENT/d3.sum().EVENT
    d3["DIST_NON_EVENT"] = d3.NONEVENT/d3.sum().NONEVENT
    print(np.log(d3.DIST_EVENT/d3.DIST_NON_EVENT))
    d3["WOE"] = np.log(d3.DIST_EVENT/d3.DIST_NON_EVENT)
    d3["IV"] = (d3.DIST_EVENT-d3.DIST_NON_EVENT)*np.log(d3.DIST_EVENT/d3.DIST_NON_EVENT)
    d3["VAR_NAME"] = "VAR"
    d3 = d3[['VAR_NAME','MIN_VALUE', 'MAX_VALUE', 'COUNT', 'EVENT', 'EVENT_RATE', 'NONEVENT', 'NON_EVENT_RATE', 'DIST_EVENT','DIST_NON_EVENT','WOE', 'IV']]       
    d3 = d3.replace([np.inf, -np.inf], 0)
    d3.IV = d3.IV.sum()
    
    return(d3)

def char_bin(Y, X):
        
    df1 = pd.DataFrame({"X": X, "Y": Y})
    justmiss = df1[['X','Y']][df1.X.isnull()]
    notmiss = df1[['X','Y']][df1.X.notnull()]    
    df2 = notmiss.groupby('X',as_index=True)
    d3 = pd.DataFrame({},index=[])
    d3["COUNT"] = df2.count().Y
    d3["MIN_VALUE"] = df2.sum().Y.index
    d3["MAX_VALUE"] = d3["MIN_VALUE"]
    d3["EVENT"] = df2.sum().Y
    d3["NONEVENT"] = df2.count().Y - df2.sum().Y
    
    if len(justmiss.index) > 0:
        d4 = pd.DataFrame({'MIN_VALUE':np.nan},index=[0])
        d4["MAX_VALUE"] = np.nan
        d4["COUNT"] = justmiss.count().Y
        d4["EVENT"] = justmiss.sum().Y
        d4["NONEVENT"] = justmiss.count().Y - justmiss.sum().Y
        d3 = d3.append(d4,ignore_index=True)
    
    d3["EVENT_RATE"] = d3.EVENT/d3.COUNT
    d3["NON_EVENT_RATE"] = d3.NONEVENT/d3.COUNT
    d3["DIST_EVENT"] = d3.EVENT/d3.sum().EVENT
    d3["DIST_NON_EVENT"] = d3.NONEVENT/d3.sum().NONEVENT
    d3["WOE"] = np.log(d3.DIST_EVENT/d3.DIST_NON_EVENT)
    d3["IV"] = (d3.DIST_EVENT-d3.DIST_NON_EVENT)*np.log(d3.DIST_EVENT/d3.DIST_NON_EVENT)
    d3["VAR_NAME"] = "VAR"
    d3 = d3[['VAR_NAME','MIN_VALUE', 'MAX_VALUE', 'COUNT', 'EVENT', 'EVENT_RATE', 'NONEVENT', 'NON_EVENT_RATE', 'DIST_EVENT','DIST_NON_EVENT','WOE', 'IV']]      
    d3 = d3.replace([np.inf, -np.inf], 0)
    d3.IV = d3.IV.sum()
    #print("hi",d3.IV )
    d3 = d3.reset_index(drop=True)
    
    return(d3)

def data_vars(df1, target):
    import traceback
    
    
    ### Extract raw traceback from error in one of the two sub functions
    ### assign traceback elemnts to variables
    stack = traceback.extract_stack()
    filename, lineno, function_name, code = stack[-2]
    
    ###
    vars_name = re.compile(r'\((.*?)\).*$').search(code).groups()[0]
    final = (re.findall(r"[\w']+", vars_name))[-1]
    
    
    ### get column names from df1
    x = df1.dtypes.index
    
    count = -1
    ### Loop through columns
    for i in x:
        print(i)
        if i.upper() not in (final.upper()):
            ### test if numeric and not a one-hot encoding
            if np.issubdtype(df1[i], np.number) and len(pd.Series.unique(df1[i])) > 2:
                #print("Number and unique value greater than 2")
                ###  pass target and feature to 'mono_bin'
                conv = mono_bin(target, df1[i])
                
                ### assign feature name to 'conv'
                conv["VAR_NAME"] = i
                count = count + 1
            else:
                #print("I am here 2")
                ###  pass target and feature to 'char_bin'
                conv = char_bin(target, df1[i])
                conv["VAR_NAME"] = i            
                count = count + 1

            ### First time run through the loop where count==0,
            ### create new df from current
            if count == 0:
                iv_df = conv
            ### on subsequent loops append rows to bottom of 'iv_df'
            ### of next feature and scoring calcs
            else:
                iv_df = iv_df.append(conv,ignore_index=True)
    ### aggregate 'iv_df' taking the maximum ?correlation? score 
    ### for each feature and creating a new summary df with columns 
    ### 'VAR_NAME' & 'IV'
    iv = pd.DataFrame({'IV':iv_df.groupby('VAR_NAME').IV.max()})
    iv = iv.reset_index()
    ### return detailed df with all computed features
    ### and summary of only max values and feature names
    return(iv_df,iv)

In [11]:
y = train.purchase
#X = pd.get_dummies(train[['channelGrouping']])
#X = pd.get_dummies(train[['city']])

iv_df, iv = data_vars(X,y)

isMobile
hits
0   -7.540655
1    1.064957
dtype: float64
pageviews

C:\Users\blain\Anaconda3\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

0        -inf
1   -5.992563
2    1.390519
dtype: float64
bounces
newVisits
hour
0   -0.277721
1   -0.166819
2    0.390857
dtype: float64
weekend
month
0    0.062175
1   -0.070128
dtype: float64
time
0   -0.454482
1    0.313858
dtype: float64
timeDiffLastVisit
0   -0.831835
1    0.000113
dtype: float64
countryPopulation
0   -2.438479
1    0.700114
dtype: float64
countryGDP
0   -2.518802
1    0.707667
dtype: float64
countryLE
0    0.260456
1   -2.197908
dtype: float64
keywordStore
keywordMerch
keywordShirt
keywordGoogle
keywordYoutube
keywordShop

C:\Users\blain\Anaconda3\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

keywordApparel
keyword_(Remarketing/Content targeting)
keyword_(User vertical targeting)
keyword_(automatic matching)
keyword_(content targeting)
keyword_(not provided)
keyword_search
channelGrouping_(Other)
channelGrouping_Affiliates
channelGrouping_Direct
channelGrouping_Display
channelGrouping_Organic Search
channelGrouping_Paid Search
channelGrouping_Referral
channelGrouping_Social
browser_Amazon Silk
browser_Android Webview
browser_Chrome
browser_Edge
browser_Firefox
browser_Internet Explorer
browser_Opera
browser_Other
browser_Safari
browser_Safari (in-app)
operatingSystem_Android
operatingSystem_Chrome OS
operatingSystem_Linux
operatingSystem_Macintosh
operatingSystem_Other
operatingSystem_Windows
operatingSystem_Windows Phone
operatingSystem_iOS
deviceCategory_desktop
deviceCategory_mobile
deviceCategory_tablet
subContinent_Australasia
subContinent_Caribbean
subContinent_Central America
subContinent_Central Asia
subContinent_Eastern Africa
subContinent_Eastern Asia
subContinent_Eastern Europe
subContinent_Melanesia
subContinent_Micronesian Region
subContinent_Middle Africa
subContinent_Northern Africa
subContinent_Northern America
subContinent_Northern Europe
subContinent_Polynesia
subContinent_South America
subContinent_Southeast Asia
subContinent_Southern Africa
subContinent_Southern Asia
subContinent_Southern Europe
subContinent_Western Africa
subContinent_Western Asia
subContinent_Western Europe
country_Afghanistan
country_Albania
country_Algeria
country_American Samoa
country_Andorra
country_Angola
country_Anguilla
country_Antigua & Barbuda
country_Argentina
country_Armenia
country_Aruba
country_Australia
country_Austria
country_Azerbaijan
country_Bahamas
country_Bahrain
country_Bangladesh
country_Barbados
country_Belarus
country_Belgium
country_Belize
country_Benin
country_Bermuda
country_Bhutan
country_Bolivia
country_Bosnia & Herzegovina
country_Botswana
country_Brazil
country_British Virgin Islands
country_Brunei
country_Bulgaria
country_Burkina Faso
country_Burundi
country_Cambodia
country_Cameroon
country_Canada
country_Cape Verde
country_Caribbean Netherlands
country_Cayman Islands
country_Central African Republic
country_Chad
country_Chile
country_China
country_Colombia
country_Comoros
country_Congo - Brazzaville
country_Congo - Kinshasa
country_Cook Islands
country_Costa Rica
country_Croatia
country_Curaçao
country_Cyprus
country_Czechia
country_Côte d’Ivoire
country_Denmark
country_Djibouti
country_Dominica
country_Dominican Republic
country_Ecuador
country_Egypt
country_El Salvador
country_Equatorial Guinea
country_Eritrea
country_Estonia
country_Ethiopia
country_Faroe Islands
country_Fiji
country_Finland
country_France
country_French Guiana
country_French Polynesia
country_Gabon
country_Gambia
country_Georgia
country_Germany
country_Ghana
country_Gibraltar
country_Greece
country_Greenland
country_Grenada
country_Guadeloupe
country_Guam
country_Guatemala
country_Guernsey
country_Guinea
country_Guinea-Bissau
country_Guyana
country_Haiti
country_Honduras
country_Hong Kong
country_Hungary
country_Iceland
country_India
country_Indonesia
country_Iran
country_Iraq
country_Ireland
country_Isle of Man
country_Israel
country_Italy
country_Jamaica
country_Japan
country_Jersey
country_Jordan
country_Kazakhstan
country_Kenya
country_Kosovo
country_Kuwait
country_Kyrgyzstan
country_Laos
country_Latvia
country_Lebanon
country_Lesotho
country_Liberia
country_Libya
country_Liechtenstein
country_Lithuania
country_Luxembourg
country_Macau
country_Macedonia (FYROM)
country_Madagascar
country_Malawi
country_Malaysia
country_Maldives
country_Mali
country_Malta
country_Marshall Islands
country_Martinique
country_Mauritania
country_Mauritius
country_Mayotte
country_Mexico
country_Moldova
country_Monaco
country_Mongolia
country_Montenegro
country_Morocco
country_Mozambique
country_Myanmar (Burma)
country_Namibia
country_Nepal
country_Netherlands
country_New Caledonia
country_New Zealand
country_Nicaragua
country_Niger
country_Nigeria
country_Norfolk Island
country_Northern Mariana Islands
country_Norway
country_Oman
country_Pakistan
country_Palestine
country_Panama
country_Papua New Guinea
country_Paraguay
country_Peru
country_Philippines
country_Poland
country_Portugal
country_Puerto Rico
country_Qatar
country_Romania
country_Russia
country_Rwanda
country_Réunion
country_Samoa
country_San Marino
country_Saudi Arabia
country_Senegal
country_Serbia
country_Seychelles
country_Sierra Leone
country_Singapore
country_Sint Maarten
country_Slovakia
country_Slovenia
country_Somalia
country_South Africa
country_South Korea
country_Spain
country_Sri Lanka
country_St. Barthélemy
country_St. Kitts & Nevis
country_St. Lucia
country_St. Martin
country_St. Pierre & Miquelon
country_St. Vincent & Grenadines
country_Sudan
country_Suriname
country_Swaziland
country_Sweden
country_Switzerland
country_Syria
country_São Tomé & Príncipe
country_Taiwan
country_Tajikistan
country_Tanzania
country_Thailand
country_Timor-Leste
country_Togo
country_Trinidad & Tobago
country_Tunisia
country_Turkey
country_Turkmenistan
country_Turks & Caicos Islands
country_U.S. Virgin Islands
country_Uganda
country_Ukraine
country_United Arab Emirates
country_United Kingdom
country_United States
country_Uruguay
country_Uzbekistan
country_Vanuatu
country_Venezuela
country_Vietnam
country_Yemen
country_Zambia
country_Zimbabwe
country_Åland Islands
city_'s Hertogenbosch
city_(not set)
city_Aalborg
city_Aalen
city_Aberdeen
city_Abu Dhabi
city_Adana
city_Adelaide
city_Ahmedabad
city_Akron
city_Alba
city_Alba Iulia
city_Alexandria
city_Alicante
city_Allendale Charter Township
city_Almaty
city_Almeria
city_Altrincham
city_Amberg
city_Amersfoort
city_Amherst
city_Amsterdam
city_Amã
city_Anaheim
city_Ankara
city_Ann Arbor
city_Annecy-le-Vieux
city_Antalya
city_Antwerp
city_Appleton
city_Arequipa
city_Arnhem
city_Ashburn
city_Asuncion
city_Athens
city_Atibaia
city_Atlanta
city_Atwater
city_Auckland
city_Austin
city_Avon
city_Aydin
city_Baku
city_Ballinger
city_Baltimore
city_Bandung
city_Bangkok
city_Barcelona
city_Barnsley
city_Barranquilla
city_Barrie
city_Bath
city_Beijing
city_Beirut
city_Bekasi
city_Belagavi
city_Belgrade
city_Bellevue
city_Bellflower
city_Bellingham
city_Belo Horizonte
city_Bengaluru
city_Berkeley
city_Berlin
city_Bhubaneswar
city_Bien Hoa
city_Bilbao
city_Birkenes
city_Birmingham
city_Boardman
city_Bogota
city_Boise
city_Bologna
city_Bordeaux
city_Boston
city_Bothell
city_Boulder
city_Bournemouth
city_Bozeman
city_Brampton
city_Brasilia
city_Bratislava
city_Breda
city_Bremen
city_Brest
city_Brisbane
city_Bristol
city_Brno
city_Brookline
city_Bruges
city_Brussels
city_Bucharest
city_Budapest
city_Buenos Aires
city_Buon Ma Thuot
city_Burlington
city_Burnaby
city_Bursa
city_Byron
city_Cabimas
city_Cagliari
city_Cairo
city_Calgary
city_Cali
city_Cambridge
city_Camden
city_Campbell
city_Campinas
city_Can Tho
city_Cancun
city_Canterbury
city_Cao Lanh
city_Cape Town
city_Caracas
city_Cardiff
city_Carrollton
city_Casablanca
city_Cebu City
city_Chambery
city_Chamblee
city_Chandigarh
city_Charlotte
city_Charlottesville
city_Charlottetown
city_Chennai
city_Chevilly Larue
city_Chicago
city_Chico
city_Chino
city_Chisinau
city_Chiyoda
city_Chuo
city_Cincinnati
city_Ciudad Real
city_Clermont-Ferrand
city_Cluj-Napoca
city_Coffeyville
city_Coimbatore
city_College Park
city_Collegeville
city_Cologne
city_Colombo
city_Columbia
city_Columbus
city_Copenhagen
city_Cordoba
city_Cork
city_Council Bluffs
city_Courbevoie
city_Coventry
city_Cuiaba
city_Culiacan
city_Culpeper
city_Cupertino
city_Curitiba
city_Cyberjaya
city_Da Nang
city_Dacun Township
city_Daegu
city_Dahlonega
city_Dalat
city_Dallas
city_Daly City
city_Danville
city_Davao City
city_Decin
city_Deep River
city_Denver
city_Depok
city_Detroit
city_Deva
city_Dhaka
city_Dnipro
city_Doha
city_Douglasville
city_Druid Hills
city_Dubai
city_Dublin
city_Dundalk
city_Dusseldorf
city_East Lansing
city_Eau Claire
city_Edison
city_Edmonton
city_Egham
city_Eindhoven
city_El Paso
city_Elche
city_Erode
city_Erzurum
city_Esbjerg
city_Eskisehir
city_Evans
city_Evanston
city_Faisalabad
city_Fareham
city_Farmington Hills
city_Faro
city_Florianopolis
city_Forest Park

city_Fort Collins
city_Fort Worth
city_Fortaleza
city_Frankfurt
city_Frederiksberg
city_Fremont
city_Fresno
city_Fukui
city_Furth
city_Gatineau
city_Gaziantep
city_Geneva
city_Ghent
city_Gijon
city_Glasgow
city_Goiania
city_Goose Creek
city_Gothenburg
city_Granada
city_Greer
city_Greve Strand
city_Greystones
city_Groningen
city_Guadalajara
city_Guangzhou
city_Guatemala City
city_Gurgaon
city_Guwahati
city_Ha Tinh
city_Hai Duong
city_Hai Phong
city_Hallein
city_Hamburg
city_Hamden
city_Hangzhou
city_Hanoi
city_Hayward
city_Helsinki
city_Hermosillo
city_Herzliya
city_Ho Chi Minh City
city_Hoi An
city_Hong Kong
city_Honolulu
city_Houston
city_Hradec Kralove
city_Hua Hin
city_Hue
city_Hukou Township
city_Hyderabad
city_Iasi
city_Indianapolis
city_Indore
city_Ipoh
city_Irvine
city_Islamabad
city_Issy-les-Moulineaux
city_Istanbul
city_Izmir
city_Jacksonville
city_Jaipur
city_Jakarta
city_Jeddah
city_Jersey City
city_Johnson City
city_Johor Bahru
city_Kalamazoo
city_Kampar
city_Kansas City
city_Karachi
city_Katowice
city_Kayseri
city_Kharagpur
city_Kharkiv
city_Kiev
city_Kirkland
city_Kiryat Ono
city_Kitchener
city_Kochi
city_Kolkata
city_Konya
city_Kortrijk
city_Kosice
city_Koszalin
city_Kovrov
city_Krakow
city_Kuala Lumpur
city_Kumamoto
city_Kuwait City
city_Kyiv
city_La Chorrera
city_La Victoria
city_LaFayette
city_Lagos
city_Laguna Beach
city_Lahore
city_Lake Oswego
city_Las Vegas
city_Lausanne
city_Lawrence Township
city_Leeds
city_Lehi
city_Leiria
city_Lenoir
city_Leon
city_Leusden
city_Leuven
city_Lewisville
city_Lexington
city_Lille
city_Lincoln
city_Lisbon
city_Liverpool
city_Ljubljana
city_London
city_Longtan District
city_Los Angeles
city_Los Gatos
city_Louisville
city_Lucknow
city_Ludhiana
city_Luxembourg City
city_Lviv
city_Lyon
city_Madison
city_Madrid
city_Makassar
city_Makati
city_Malaga
city_Manaus
city_Manchester
city_Manila
city_Mankato
city_Mar del Plata
city_Maracaibo
city_Marlboro
city_Marseille
city_McAllen
city_Mechelen
city_Medan
city_Medellin
city_Medina
city_Melbourne
city_Memphis
city_Menlo Park
city_Mersin
city_Metz
city_Mexico City
city_Miami
city_Miami Beach
city_Milan
city_Milpitas
city_Milwaukee
city_Minato
city_Minneapolis
city_Minsk
city_Minxiong Township
city_Mississauga
city_Miyazaki
city_Molesey
city_Monterrey
city_Montevideo
city_Montigny-le-Bretonneux
city_Montreal
city_Montreuil
city_Moscow
city_Mountain View
city_Mueang Chiang Mai District
city_Mueang Khon Kaen District
city_Mueang Nakhon Ratchasima District
city_Mueang Phitsanulok District
city_Mueang Songkhla District
city_Mumbai
city_Munich
city_Muntinlupa
city_My Tho
city_Nagano
city_Nagoya
city_Naha
city_Nairobi
city_Nakhon Pathom
city_Nam Djinh
city_Nanded
city_Nantes
city_Naples
city_Nashville
city_Navi Mumbai
city_Nea Erythraia
city_Neipu Township
city_Netanya
city_New Delhi
city_New Orleans
city_New Westminster
city_New York
city_Newark
city_Newtonville
city_Nha Trang
city_Nice
city_Ningbo
city_Noida
city_Norfolk
city_Normandy
city_North Attleborough
city_North Richland Hills
city_Nottingham
city_Nuremberg
city_Oakland
city_Odense
city_Odessa
city_Oegstgeest
city_Okemos
city_Olomouc
city_Omaha
city_Oneonta
city_Oradea
city_Orem
city_Orlando
city_Osaka
city_Oshkosh
city_Osijek
city_Oslo
city_Ostrava
city_Ottawa
city_Oude Meer
city_Overland Park
city_Oviedo
city_Oxford
city_Padua
city_Palo Alto
city_Panama City
city_Paradise
city_Paris
city_Parma
city_Parsippany-Troy Hills
city_Pasig
city_Patna
city_Perth
city_Pescara
city_Pessac
city_Petaling Jaya
city_Petergof
city_Phan Thiet
city_Philadelphia
city_Phnom Penh
city_Phoenix
city_Pinamar
city_Piscataway Township
city_Pittsburgh
city_Piura
city_Plano
city_Pleasanton
city_Pleiku
city_Pontivy
city_Portland
city_Porto Alegre
city_Poznan
city_Pozuelo de Alarcon
city_Prague
city_Prato
city_Pryor
city_Pueblo
city_Pune
city_Quang Ngai
city_Quebec City
city_Quezon City
city_Qui Nhon
city_Quimper
city_Quito
city_Rach Gia
city_Raleigh
city_Ramat Gan
city_Randburg
city_Recife
city_Redmond
city_Redondo Beach
city_Redwood City
city_Reims
city_Rexburg
city_Ribeirao Preto
city_Richardson
city_Ridgewood
city_Riga
city_Rio de Janeiro
city_Rishon LeTsiyon
city_Riverside
city_Riyadh
city_Rockwood
city_Rome
city_Rosario
city_Roskilde
city_Rotterdam
city_Rzeszow
city_Sabadell
city_Sacramento
city_Saint Paul
city_Saint Petersburg
city_Saint Polten
city_Saint-Ouen-l'Aumone
city_Sakai
city_Salem
city_Salford
city_Salt Lake City
city_Salvador
city_Salzburg
city_Samsun
city_San Antonio
city_San Bruno
city_San Carlos
city_San Diego
city_San Francisco
city_San Jose
city_San Marcos
city_San Mateo
city_San Salvador
city_Sandton
city_Sandy
city_Sandy Springs
city_Sant Cugat del Valles
city_Santa Ana
city_Santa Clara
city_Santa Fe
city_Santa Monica
city_Santiago
city_Santiago de Queretaro
city_Santiago de Surco
city_Sao Paulo
city_Sapporo
city_Saratoga
city_Schagen
city_Seattle
city_Seclin
city_Semarang
city_Seongnam-si
city_Seoul
city_Seville
city_Shah Alam
city_Shanghai
city_Sharjah
city_Sheffield
city_Sherbrooke
city_Shibuya
city_Shinjuku
city_Shiocton
city_Sibiu
city_Singapore
city_Skopje
city_Smyrna
city_Sofia
city_South El Monte
city_South San Francisco
city_Spaichingen
city_Springfield
city_St. John's
city_St. Louis
city_Stanford
city_Stockholm
city_Stuttgart
city_Subang Jaya
city_Sunnyvale
city_Surabaya
city_Surat
city_Sydney
city_Syracuse
city_Szczecin
city_Taguig
city_Talence
city_Tallahassee
city_Tallinn
city_Tampa
city_Tampere
city_Taoyuan District
city_Targu Mures
city_Tbilisi
city_Tel Aviv-Yafo
city_Telford
city_Tempe
city_Thai Binh
city_Thai Nguyen
city_Thane
city_Thanh Hoa
city_The Dalles
city_The Hague
city_Thessaloniki
city_Thornton
city_Tigard
city_Tijuana
city_Timisoara
city_Tirana
city_Toledo
city_Toronto
city_Toufen City
city_Towson
city_Trabzon
city_Tucson
city_Tunis
city_Turin
city_Ulaanbaatar
city_Union City
city_University Park
city_Utrecht
city_Vadodara
city_Valencia
city_Valparaiso
city_Vancouver
city_Vannes
city_Vejle
city_Viby
city_Vienna
city_Vila Velha
city_Villafranca del Castillo
city_Villanova
city_Villeneuve-d'Ascq
city_Vilnius
city_Vincennes
city_Vinh
city_Vladimir
city_Vladivostok
city_Vung Tau
city_Walnut Creek
city_Warsaw
city_Washington
city_Waterloo
city_Watford
city_Weingarten
city_Wellesley
city_Wellington
city_Westlake Village
city_Westville
city_Wheaton
city_Wheeling
city_White Plains
city_Whitewater
city_Winnipeg
city_Wollongong
city_Woodbridge Township
city_Wrexham
city_Wroclaw
city_Yokohama
city_Zagreb
city_Zamudio
city_Zaoqiao Township
city_Zapopan
city_Zaragoza
city_Zaventem
city_Zhongli District
city_Zhudong Township
city_Zurich
city_Zwolle
city_not available in demo dataset
state_Arizona
state_California
state_Colorado
state_Connecticut
state_Florida
state_Georgia
state_Hawaii
state_Idaho
state_Illinois
state_Indiana
state_Iowa
state_Kansas
state_Kentucky
state_Louisiana
state_Maryland
state_Massachusetts
state_Michigan
state_Minnesota
state_Missouri
state_Montana
state_Nebraska
state_Nevada
state_New Jersey
state_New York
state_North Carolina
state_NotUS
state_Ohio
state_Oklahoma
state_Oregon
state_Pennsylvania
state_South Carolina
state_Tennessee
state_Texas
state_Utah
state_Virginia
state_Washington
state_West Virginia
state_Wisconsin
campaign_(not set)
campaign_AW - Accessories
campaign_AW - Apparel
campaign_AW - Dynamic Search Ads Whole Site
campaign_AW - Electronics
campaign_All Products
campaign_Data Share
campaign_Data Share Promo
campaign_Retail (DO NOT EDIT owners nophakun and tianyu)
campaign_test-liyuhz
source_(direct)
source_LumpedNoConversion
source_Partners
source_ask
source_basecamp.com
source_bing
source_calendar.google.com
source_chat.google.com
source_connect.googleforwork.com
source_dealspotr.com
source_dfa
source_docs.google.com
source_duckduckgo.com
source_facebook.com
source_gatewaycdi.com
source_gdeals.googleplex.com
source_google
source_google.com
source_googleux.perksplus.com
source_groups.google.com
source_keep.google.com
source_l.facebook.com
source_l.messenger.com
source_m.facebook.com
source_mail.aol.com
source_mail.google.com
source_mall.googleplex.com
source_mg.mail.yahoo.com
source_moma.corp.google.com
source_outlook.live.com
source_phandroid.com

source_pinterest.com
source_plus.google.com
source_quora.com
source_reddit.com
source_search.myway.com
source_search.xfinity.com
source_seroundtable.com
source_siliconvalley.about.com
source_sites.google.com
source_t.co
source_trainup.withgoogle.com
source_us-mg5.mail.yahoo.com
source_yahoo
source_youtube.com

In [12]:
iv.sort_values('IV',ascending=False)

                           VAR_NAME            IV
905                            hits  5.636926e+00
931                       pageviews  2.501622e+00
1026  subContinent_Northern America  2.013279e+00
892           country_United States  1.883897e+00
678                      countryGDP  1.566860e+00
...                             ...           ...
17              campaign_Data Share  1.261294e-12
866              country_St. Martin  1.261294e-12
828          country_Norfolk Island  1.261294e-12
863          country_St. Barthélemy  1.261294e-12
875     country_São Tomé & Príncipe  1.261294e-12

[1040 rows x 2 columns]

In [13]:
iv[iv.IV>0.01].sort_values('IV',ascending=False)

                           VAR_NAME        IV
905                            hits  5.636926
931                       pageviews  2.501622
1026  subContinent_Northern America  2.013279
892           country_United States  1.883897
678                      countryGDP  1.566860
...                             ...       ...
206                     city_Dublin  0.011650
700                 country_Belgium  0.011110
860             country_South Korea  0.011066
419                  city_New Delhi  0.010398
602              city_Tel Aviv-Yafo  0.010126

[116 rows x 2 columns]

### Now assessing multicollinearity with variance inflation factor

Leaving variables with a high IV (>0.8) becuase the problem is not just to predict if purchase or not, but the size of the purchases for each user. 'hits' and 'pageviews' are 2 of only a small number of continuous variables in the data.

In [88]:
feats = list(iv.loc[iv.IV>0.01,'VAR_NAME'])
X2 = X[feats]

In [86]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

def iterate_vif(df, vif_threshold=5, max_vif=6):
    count = 0
    while max_vif > vif_threshold:
        count += 1
        print("Iteration # "+str(count))
        
        ### Create data frame with features column and 
        ### variance inflation factor column
        vif = pd.DataFrame()
        vif["VIFactor"] = [variance_inflation_factor(df.values, i) for i in range(df.shape[1])]
        vif["features"] = df.columns
        
        
        
        if vif['VIFactor'].max() > vif_threshold:
            print('Removing %s with VIF of %f' % (vif[vif['VIFactor'] == vif['VIFactor'].max()]['features'].values[0], vif['VIFactor'].max()))
            df = df.drop(vif[vif['VIFactor'] == vif['VIFactor'].max()]['features'].values[0], axis=1)
            max_vif = vif['VIFactor'].max()
            #if count==45:
                #print('early stop for plotting intermediate step')
                #return df, vif.sort_values('VIFactor')  
        else:
            print('Complete')
            return df, vif.sort_values('VIFactor')

In [89]:
#final_df,vif = iterate_vif(X2)

Iteration # 1
Removing countryGDP with VIF of 13665.770702
Iteration # 2
Removing channelGrouping_Affiliates with VIF of 8574.478605
Iteration # 3
Removing countryLE with VIF of 5546.885285
Iteration # 4
Removing time with VIF of 2557.517592
Iteration # 5
Removing source_Partners with VIF of 2048.434755
Iteration # 6
Removing isMobile with VIF of 984.920352
Iteration # 7
Removing state_New York with VIF of 415.740056
Iteration # 8
Removing deviceCategory_desktop with VIF of 169.377869
Iteration # 9
Removing keyword_(not provided) with VIF of 64.120647
Iteration # 10
Removing state_NotUS with VIF of 56.538822
Iteration # 11
Removing state_Illinois with VIF of 53.914906
Iteration # 12
Removing subContinent_Northern America with VIF of 49.690311
Iteration # 13
Removing pageviews with VIF of 41.735349
Iteration # 14
Removing countryPopulation with VIF of 40.893756
Iteration # 15
Removing deviceCategory_mobile with VIF of 40.438496
Iteration # 16
Removing operatingSystem_Windows with VIF of 30.710044
Iteration # 17
Removing channelGrouping_Social with VIF of 19.183943
Iteration # 18
Removing channelGrouping_Organic Search with VIF of 19.006332
Iteration # 19
Removing subContinent_Southern Asia with VIF of 15.758345
Iteration # 20
Removing browser_Chrome with VIF of 12.984324
Iteration # 21
Removing subContinent_Northern Europe with VIF of 11.399515
Iteration # 22
Removing keyword_search with VIF of 10.277164
Iteration # 23
Removing subContinent_Western Europe with VIF of 8.732675
Iteration # 24
Removing state_Michigan with VIF of 7.683768
Iteration # 25
Removing country_Australia with VIF of 7.416206
Iteration # 26
Removing subContinent_Central America with VIF of 6.795589
Iteration # 27
Removing subContinent_Eastern Europe with VIF of 6.463831
Iteration # 28
Removing state_California with VIF of 6.083727
Iteration # 29
Removing subContinent_Eastern Asia with VIF of 5.589804
Iteration # 30
Complete

That probably took about 12 hours... I'll print the features out in case I need them

In [129]:
print(feats)

['bounces', 'browser_Android Webview', 'browser_Firefox', 'browser_Opera', 'browser_Safari', 'browser_Safari (in-app)', 'campaign_Data Share Promo', 'channelGrouping_Referral', 'city_(not set)', 'city_Ann Arbor', 'city_Austin', 'city_Bangkok', 'city_Bengaluru', 'city_Cambridge', 'city_Chicago', 'city_Dublin', 'city_Istanbul', 'city_London', 'city_Los Angeles', 'city_Mountain View', 'city_Mumbai', 'city_New Delhi', 'city_New York', 'city_Paris', 'city_San Bruno', 'city_San Francisco', 'city_Seattle', 'city_Sunnyvale', 'city_Sydney', 'city_Tel Aviv-Yafo', 'city_Warsaw', 'city_not available in demo dataset', 'country_Argentina', 'country_Belgium', 'country_Brazil', 'country_Czechia', 'country_Denmark', 'country_France', 'country_Germany', 'country_India', 'country_Indonesia', 'country_Ireland', 'country_Israel', 'country_Italy', 'country_Japan', 'country_Malaysia', 'country_Mexico', 'country_Netherlands', 'country_Pakistan', 'country_Peru', 'country_Philippines', 'country_Poland', 'country_Romania', 'country_Russia', 'country_Singapore', 'country_South Korea', 'country_Spain', 'country_Sweden', 'country_Taiwan', 'country_Thailand', 'country_Turkey', 'country_Ukraine', 'country_United Kingdom', 'country_United States', 'deviceCategory_tablet', 'hits', 'hour', 'newVisits', 'operatingSystem_Android', 'operatingSystem_Chrome OS', 'operatingSystem_Linux', 'operatingSystem_Macintosh', 'operatingSystem_iOS', 'source_google', 'source_google.com', 'source_mall.googleplex.com', 'source_youtube.com', 'state_Massachusetts', 'state_Texas', 'state_Washington', 'subContinent_Australasia', 'subContinent_Northern Africa', 'subContinent_South America', 'subContinent_Southeast Asia', 'subContinent_Southern Europe', 'subContinent_Western Asia', 'weekend']

In [14]:
final_df = X[['bounces', 'browser_Android Webview', 'browser_Firefox', 'browser_Opera', 'browser_Safari', 'browser_Safari (in-app)', 'campaign_Data Share Promo', 'channelGrouping_Referral', 'city_(not set)', 'city_Ann Arbor', 'city_Austin', 'city_Bangkok', 'city_Bengaluru', 'city_Cambridge', 'city_Chicago', 'city_Dublin', 'city_Istanbul', 'city_London', 'city_Los Angeles', 'city_Mountain View', 'city_Mumbai', 'city_New Delhi', 'city_New York', 'city_Paris', 'city_San Bruno', 'city_San Francisco', 'city_Seattle', 'city_Sunnyvale', 'city_Sydney', 'city_Tel Aviv-Yafo', 'city_Warsaw', 'city_not available in demo dataset', 'country_Argentina', 'country_Belgium', 'country_Brazil', 'country_Czechia', 'country_Denmark', 'country_France', 'country_Germany', 'country_India', 'country_Indonesia', 'country_Ireland', 'country_Israel', 'country_Italy', 'country_Japan', 'country_Malaysia', 'country_Mexico', 'country_Netherlands', 'country_Pakistan', 'country_Peru', 'country_Philippines', 'country_Poland', 'country_Romania', 'country_Russia', 'country_Singapore', 'country_South Korea', 'country_Spain', 'country_Sweden', 'country_Taiwan', 'country_Thailand', 'country_Turkey', 'country_Ukraine', 'country_United Kingdom', 'country_United States', 'deviceCategory_tablet', 'hits', 'hour', 'newVisits', 'operatingSystem_Android', 'operatingSystem_Chrome OS', 'operatingSystem_Linux', 'operatingSystem_Macintosh', 'operatingSystem_iOS', 'source_google', 'source_google.com', 'source_mall.googleplex.com', 'source_youtube.com', 'state_Massachusetts', 'state_Texas', 'state_Washington', 'subContinent_Australasia', 'subContinent_Northern Africa', 'subContinent_South America', 'subContinent_Southeast Asia', 'subContinent_Southern Europe', 'subContinent_Western Asia', 'weekend']]

In [15]:
feats = list(final_df.columns)
iv[iv.VAR_NAME.isin(feats)].sort_values('IV',ascending=False)

                       VAR_NAME        IV
905                        hits  5.636926
892       country_United States  1.883897
976          source_youtube.com  1.373643
958  source_mall.googleplex.com  0.892687
922                   newVisits  0.686432
..                          ...       ...
206                 city_Dublin  0.011650
700             country_Belgium  0.011110
860         country_South Korea  0.011066
419              city_New Delhi  0.010398
602          city_Tel Aviv-Yafo  0.010126

[87 rows x 2 columns]

### Pre-proccesing for modelling 
1. Put the data back together with the purchase amount, visitor id and visit number

In [16]:
df = pd.concat([ final_df,train[['fullVisitorId','visitNumber','dollars']] ], axis=1).sort_values(['fullVisitorId','visitNumber']).reset_index(drop=True)

In [17]:
df.head()

,bounces,browser_Android Webview,browser_Firefox,browser_Opera,browser_Safari,browser_Safari (in-app),campaign_Data Share Promo,channelGrouping_Referral,city_(not set),city_Ann Arbor,...,subContinent_Australasia,subContinent_Northern Africa,subContinent_South America,subContinent_Southeast Asia,subContinent_Southern Europe,subContinent_Western Asia,weekend,fullVisitorId,visitNumber,dollars
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4823595352351,1,0.0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,5103959234087,1,0.0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,10278554503158,1,0.0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,20424342248747,1,0.0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,26722803385797,1,0.0

In [18]:
print(df.fullVisitorId.value_counts().head())

824839726118485274     242
1856749147915772585    188
3608475193341679870    187
7634897085866546110    144
3269834865385146569    144
Name: fullVisitorId, dtype: int64

The maximum number of repeated visits is 242.

In [19]:
time_steps = 242 ### maximum number of repeated visits
features = 87 ### features for predicting each time step

Now I need to reshape the data to (users,time_steps,features) where the time series is the purchase amount from the GStore reverse filled from the right.  So if a user has 3 visits then them time series will look like [0,0,0,0,...10,0,35], something like that.

In [20]:
shape = tuple([df.fullVisitorId.nunique(),time_steps,features])
arr = np.full(shape,np.nan)

MemoryError: Unable to allocate 113. GiB for an array with shape (722668, 242, 87) and data type float64

Problem with my plan to model the data with an LSTM.  My computer cannot handle the size of the 3 dimensional array that is needed.  
___
But a tensorflow model trains and processes in batches!  Maybe I could seperate the data into train, validation and test sets by randomly choosing users.  Then I could convert a batch of users into the 3D time series format as input into the LSTM model... maybe with `tf.keras.preprocessing.sequence.TimeseriesGenerator`
___
I'll consult with Rahul. As a fallback I can use a standard deep learning model instead with `visitNumber` as a feature.  That still leaves the problem of how to collect all of each users purchases at the end of the network and minimize that error.